### ISSUE TITLE
Travis build failed 

### ISSUE THREAD

**Issue by Harlber** [Harlber/Moose#16]
``` java
Caused by: java.lang.NullPointerException
    at com.squareup.leakcanary.internal.LeakCanaryInternals.isInServiceProcess(LeakCanaryInternals.java:130)
    at com.squareup.leakcanary.LeakCanary.isInAnalyzerProcess(LeakCanary.java:146)
    at com.squareup.leakcanary.LeakCanary.install(LeakCanary.java:48)
    at com.squareup.leakcanary.LeakCanary.install(LeakCanary.java:37)
    at moose.com.ac.AppApplication.onCreate(AppApplication.java:49)
    at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:140)
    at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
    ... 26 more
```

**Comment by Harlber** [comment]
See [http://stackoverflow.com/questions/30169678/nullpointerexception-from-leakcanary-when-running-robolectric-tests](http://stackoverflow.com/questions/30169678/nullpointerexception-from-leakcanary-when-running-robolectric-tests)
<p>See [square/leakcanary issues#143](https://github.com/square/leakcanary/issues/143)
