### ISSUE TITLE
Activity  not resumed

### ISSUE THREAD

**Issue by Harlber** [Harlber/Moose#7]
``` java
Performing stop of activity that is not resumed: {ac.moose.com.moose/moose.com.ac.MainActivity}
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread: java.lang.RuntimeException: Performing stop of activity that is not resumed: {ac.moose.com.moose/moose.com.ac.MainActivity}
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread:     at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3394)
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread:     at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3475)
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread:     at android.app.ActivityThread.access$1100(ActivityThread.java:148)
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread:     at android.os.Looper.loop(Looper.java:135)
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread:     at android.app.ActivityThread.main(ActivityThread.java:5310)
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread:     at java.lang.reflect.Method.invoke(Native Method)
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread:     at java.lang.reflect.Method.invoke(Method.java:372)
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
10-18 12:16:32.561 21470-21470/ac.moose.com.moose E/ActivityThread:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

**Comment by Harlber** [comment]
See the same issue in [StackOverFlow](http://stackoverflow.com/questions/21947675/android-4-4-2-java-lang-runtimeexception-performing-stop-of-activity-that-is/23246159#23246159)
